tags:
- name: wallpapers
  description: wallpapers API

paths:
# [GET] wallpapers
  /wallpapers:
    get:
      tags:
      - wallpapers
      summary: Find All Wallpapers
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [POST] wallpapers
    post:
      tags:
      - wallpapers
      summary: Add Wallpaper
      parameters:
      - name: body
        in: body
        description: wallpaper Data
        required: true
        schema:
          $ref: '#/definitions/wallpapers'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [GET] wallpapers/id
  /wallpapers/{id}:
    get:
      tags:
      - wallpapers
      summary: Find Wallpaper By Id
      parameters:
      - name: id
        in: path
        description: Wallpaper Id
        required: true
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [PUT] wallpapers/id
    put:
      tags:
      - wallpapers
      summary: Update Wallpaper By Id
      parameters:
      - name: id
        in: path
        description: wallpaper Id
        required: true
      - name: body
        in: body
        description: wallpaper Data
        required: true
        schema:
          $ref: '#/definitions/wallpapers'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [DELETE] wallpapers/id
    delete:
      tags:
      - wallpapers
      summary: Delete Wallpaper By Id
      parameters:
      - name: id
        in: path
        description: wallpaper Id
        required: true
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# definitions
definitions:
  wallpapers:
    type: object
    required:
        - email
        - password
    properties:
      email:
        type: string
        description: wallpaper Email
      password:
        type: string
        description: wallpaper Password

schemes:
 - https
 - http
