# baseURL
@baseURL = http://localhost:3000

###
# Find All Wallpapers
GET {{ baseURL }}/wallpapers

###
# Find Wallpaper By Id
GET {{ baseURL }}/wallpapers/1

###
# Create Wallpaper
POST {{ baseURL }}/wallpapers
Content-Type: application/json

{
    "email": "example@email.com",
    "password": "password"
}

###
# Modify Wallpaper By Id
PUT {{ baseURL }}/wallpapers/1
Content-Type: application/json

{
    "email": "example@email.com",
    "password": "password"
}

###
# Delete Wallpaper By Id
DELETE {{ baseURL }}/wallpapers/1
